Add fix and test for orient-split roundtrip multiIndex
ma-anwar/pandas pull request #3
Opened 2023-03-08 21:04 UTC by serhatgktp

- [ x] closes #50456
- [ x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ x] Added an entry in the latest `doc/source/whatsnew/v2.0.0.rst` file if fixing a bug or adding a new feature.

`pandas.DataFrame.to_json()` and `pandas.read_json()` were not forming a successful round trip (i.e. a conversion from DataFrame to JSON, and then from JSON back to DataFrame) when used with a MultiIndex DataFrame with the setting orient="split".

This was fixed by adding a case for `orient="split"` in `pandas.DataFrame.to_json()`

Test was created and added, the fix passes the test.

2023-03-08 23:51 UTC, ma-anwar requested changes
Great work, I left some suggested changes. In general I understand the iterative approach you took but I think here a functional approach will be much cleaner for your problem. Can you give my suggestion a shot?

2023-03-08 23:51 UTC, ma-anwar commented on pandas/io/json/_json.py
> +        for i in range(n):
I understand why we're doing this; we want every first element of every list grouped together, every second element of every list grouped together etc.

I think there is a much cleaner way to do this that will be more readable using the zip method. I left an example below, could you try using this instead?

```
>>> for x in zip(['a', 'b', 'c'], ['d','e','f'], ['g', 'h', 'i']):
...     print(x)
...
('a', 'd', 'g')
('b', 'e', 'h')
('c', 'f', 'i')
```

2023-03-08 23:51 UTC, ma-anwar commented on pandas/io/json/_json.py
> +        d = loads(s)
I know the pandas code base uses one letter variables for things like strings and that's why you're using s below. But for our own variables that we're defining like `d`, can you give a more descriptive name. I understand here that we're converting the string to a dict, is there a better name you can use here so it's more obvious?

2023-03-08 23:51 UTC, ma-anwar commented on pandas/io/json/_json.py
> +        new_cols_d = {i: [] for i in range(n)}
See my below comment on zip, once you incorporate that, can you see if this is necessary? I didn't give it much thought so it may be.

2023-03-08 23:51 UTC, ma-anwar commented on pandas/tests/io/json/test_pandas.py
> +    def test_roundtrip_multiindex(self):
Thanks for being ahead of schedule and adding the test. Are there any edge cases to consider? Is an empty input possible by any chance? (i.e. orient split df that's empty?) Can you check if it's path of execution will go through your code and if so that the result is as expected?

2023-03-09 00:12 UTC, serhatgktp commented on pandas/io/json/_json.py
> +        for i in range(n):
Thanks! I concur. Adding fixes now.

2023-03-09 00:20 UTC, serhatgktp commented on pandas/io/json/_json.py
> +        d = loads(s)
Done, thanks for bringing this up

2023-03-09 00:20 UTC, serhatgktp commented on pandas/tests/io/json/test_pandas.py
> +    def test_roundtrip_multiindex(self):
Good point, thanks! Adding a little intensity to the test here.

2023-03-10 15:28 UTC, ma-anwar commented on pandas/tests/io/json/test_pandas.py
> +        # Iterate over the test suite dictionary, unpacking the test name and test data
Please remove this comment, your loop speaks for itself, nj with the clean code

2023-03-10 15:28 UTC, ma-anwar commented on pandas/tests/io/json/test_pandas.py
> +                "multi_index": [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
Is there any case where we can have empty values for any of these test parameters? Any possible edge cases?

2023-03-10 19:35 UTC, serhatgktp commented on pandas/tests/io/json/test_pandas.py
> +                "multi_index": [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
Our fix actually fails this test that I wrote:
```
	"test_roundtrip_multiindex_empty_3": {
		"multi_index": [[], []],
		"cols": [[], []]
	}
```

Here's the verbose output:
```
df1:
Empty DataFrame
Columns: []
Index: [0, 1]

json_str: {"columns":[],"index":[0,1],"data":[[],[]]}  # It looks like 'index' is 
                                                       # automatically set to [0,1]

df2:
Empty DataFrame
Columns: []
Index: [0, 1]
```

And here's the error message:

```
DataFrame.columns classes are not equivalent
[left]:  Float64Index([], dtype='float64')  # df2
[right]: MultiIndex([], )                   # df1
```

To me, it seems like the discrepancy is because the DataFrame generated by `read_json()` is not created as a DataFrame with MultiIndex since the JSON string simply has no columns. Thus it would be nonsensical for the result DataFrame to have MultiIndex columns. This is an edge case, but I don't think it poses a problem.

2023-03-10 20:02 UTC, ma-anwar commented on pandas/tests/io/json/test_pandas.py
> +                "multi_index": [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
Okay so just to confirm if you use this test, the path of execution does not go through the code that we're writing for this fix right?

2023-03-11 01:10 UTC, closed without merging